---
title: "Congreso Hoy"
output: html_document
---

```{r setup, include=FALSE}
library(DBI)
library(tidyverse)
library(RMySQL)
library(highcharter)
library(readr)
library(here)

proyecto_leys <- read_csv(here("Bases de datos nuevas/proyecto_leys.csv"))
proyecto_ley_autors <- read_csv(here("Bases de datos nuevas/proyecto_ley_autors.csv"))
tipo_proyectos <- read_csv(here("Bases de datos nuevas/tipo_proyectos.csv"))
proyecto_ley_autor_otros <- read_csv(here("Bases de datos nuevas/proyecto_ley_autors, proyecto_ley_autor_otros.csv"))
corporacions <- read_csv(here("Bases de datos nuevas/corporacions.csv"))
temas <- read_csv(here("Bases de datos nuevas/temas.csv"))
proyecto_ley_estados <- read_csv(here("Bases de datos nuevas/proyecto_ley_estados.csv"))
iniciativa <- read_csv(here("Bases de datos nuevas/iniciativas.csv"))
```


# Proyectos de ley

## Número de proyectos de ley entrámite
Hace falta la base de estado de los proyectos y la de corporacions 
Se bede hacer otra variable de estado de proyecto de ley

```{r warning=FALSE, echo=FALSE, comment=FALSE, message=FALSE}
proyecto_leys %>% 
  # filter(activo == 1 && cuatrienio_id == 1) %>%
  count(corporacion_id, estado_proyecto_ley_id) %>%
  filter(estado_proyecto_ley_id %in% c(  12, 13 ,15, 17, 19, 21, 23 ,25 ,27, 29, 31, 37, 42, 43,
                         44, 45, 46, 47, 48, 49, 50, 51, 52, 54, 56, 58, 60 ,63, 64, 65, 66, 68,
                        69, 72, 73, 74, 76, 77, 78, 79, 83)) %>%
  group_by(corporacion_id) %>% 
  summarise(n=sum(n)) %>% arrange(desc(n)) %>%  
  left_join(corporacions %>%  select(corporacion_id = id, corporacion = nombre), by = "corporacion_id") %>% 
  hchart(hcaes(x = corporacion, y = n), type = "bar") %>% 
  hc_title(text = "Proyectos de ley en trámite")
```

## Origen de la iniciativa

```{r warning=FALSE, echo=FALSE, comment=FALSE, message=FALSE}
proyecto_leys %>% 
  # left_join(tbl(con, "iniciativas") %>%
  #             select(iniciativa_id= id, iniciativa = nombre) ) %>% 
  count(iniciativa_id) %>% 
  # filter(iniciativa %in%c( "Legislativa ", "Gubernamental", "Mixta", "Otras entidades ")) %>% 
  hchart(hcaes(x = iniciativa_id, y = n), type = "bar") %>% 
  hc_title(text = "Proyectos de ley por iniciativa")
```

## Temas recurrentes

```{r warning=FALSE, echo=FALSE, comment=FALSE, message=FALSE}
proyecto_leys %>% 
  # tbl(con, "proyecto_leys") %>%  
  count(tema_id) %>% 
  arrange(desc(n)) %>%  head(10) %>%  collect()%>% 
  hchart(hcaes(x = tema_id, value = n), type = "treemap")
```

## Estado de los proyectos

```{r warning=FALSE, echo=FALSE, comment=FALSE, message=FALSE}
proyecto_leys  %>%
  count(corporacion_id, estado_proyecto_ley_id) %>%
  # left_join(proyecto_ley_estados %>%
  #             select(estado_proyecto_ley_id = id, estado = nombre),
  #           by = "estado_proyecto_ley_id" ) %>%
  left_join(corporacions %>%
              select(corporacion_id = id, corporacion = nombre), by = "corporacion_id" ) %>%
  mutate(estado_proyecto_ley_id = as.character(estado_proyecto_ley_id)) %>% 
  arrange(desc(n)) %>% 
  filter(n>9) %>% 
  # hchart(hcaes(from = corporacion, to  = estado, weight =n), type = "sankey") 
  hchart(hcaes(x = estado_proyecto_ley_id, y = n, group = corporacion), type = "bar") %>% 
  hc_plotOptions(bar = list(stacking = T))
```
## Total de proyectos presentados por ministros
```{r warning=FALSE, echo=FALSE, comment=FALSE, message=FALSE}
proyecto_leys   %>% 
  # filter(legislatura_id ==24) %>% 
  left_join(iniciativa %>%
              select(iniciativa_id= id, iniciativa = nombre) ) %>% 
  mutate(iniciativa2  = case_when(iniciativa %in% c("Gubernamental", "Mixta")~ "Ministros", 
                                  T~"Otros")) %>%  
  count(iniciativa2, iniciativa)  %>% 
  arrange(desc(n)) %>%  mutate(pct = round(n*100/sum(n))) %>% 
  filter(pct != 0) %>% 
  hchart(hcaes(x = iniciativa2, y = pct, group = iniciativa),type = "bar") %>% 
  hc_plotOptions(bar = list(stacking = T)) %>% 
  hc_yAxis(reversedStacks = F)

```
