---
title: "Histórico"
output: html_document
---

```{r setup, include=FALSE}
library(DBI)
library(tidyverse)
library(RMySQL)
library(highcharter)
library(readr)
library(here)
library(lubridate)
proyecto_leys <- read_csv(here("Bases de datos nuevas/proyecto_leys.csv"))
proyecto_ley_autors <- read_csv(here("Bases de datos nuevas/proyecto_ley_autors.csv"))
tipo_proyectos <- read_csv(here("Bases de datos nuevas/tipo_proyectos.csv"))
proyecto_ley_autor_otros <- read_csv(here("Bases de datos nuevas/proyecto_ley_autors, proyecto_ley_autor_otros.csv"))
corporacions <- read_csv(here("Bases de datos nuevas/corporacions.csv"))
temas <- read_csv(here("Bases de datos nuevas/temas.csv"))
proyecto_ley_estados <- read_csv(here("Bases de datos nuevas/proyecto_ley_estados.csv"))
iniciativa <- read_csv(here("Bases de datos nuevas/iniciativas.csv"))
```

## Proyectos de ley

```{r warning=FALSE, echo=FALSE, comment=FALSE, message=FALSE}
### Total de proyectos de ley y sancionados como ley
proyecto_leys %>% 
  mutate(ley = case_when(estado_proyecto_ley_id %in% c(40)~1, T~0))  %>% 
  mutate(year = floor_date(fecha_radicacion, unit = "year")) %>%
  group_by(year ) %>%  summarise(Proyectos = n(), Ley = sum(ley)) %>% 
  gather(grupo, n, Proyectos:Ley) %>% 
  mutate(grupo = factor(grupo, c("Proyectos", "Ley"))) %>% 
  hchart(hcaes(x  = year, y =n, group = grupo),type= "area")

``` 

## Temas recurrentes
```{r warning=FALSE, echo=FALSE, comment=FALSE, message=FALSE}
proyecto_leys %>% 
  count( tema_id) %>% 
  left_join(temas %>%  select(tema_id = id, tema  = nombre)) %>% 
  arrange(desc(n)) %>%  head(10) %>% 
  hchart(hcaes(x = tema, value = n), type = "treemap")

``` 

# Días de aprobación
```{r warning=FALSE, echo=FALSE, comment=FALSE, message=FALSE}
aux <- proyecto_leys %>%
  filter(estado_proyecto_ley_id ==40) %>%
  mutate(fecha_actualizacion =as.Date(floor_date(updated_at, unit = "day"))) %>% 
  # count(tipo_proyecto_id, fecha_radicacion, fecha_actualizacion) %>%
  left_join(tipo_proyectos %>%  select(tipo_proyecto_id=id, tipo = nombre )) %>% 
  group_by(tipo) %>%
  summarise( dias_dif = round(mean(fecha_actualizacion- fecha_radicacion) %>%  as.numeric()),
             dias_min =round(min(fecha_actualizacion- fecha_radicacion) %>%  as.numeric()),
             dias_max =round(max(fecha_actualizacion- fecha_radicacion)) %>%  as.numeric()) %>% 
  arrange(desc(dias_dif))
aux %>%  
  hchart(hcaes(x = tipo, low = dias_min, high= dias_max), type = "errorbar") %>% 
  hc_add_series(aux, hcaes(x = tipo, y= dias_dif), type = "scatter") %>% 
  hc_chart(inverted = T)
  
``` 

# Composición partidista
```{r warning=FALSE, echo=FALSE, comment=FALSE, message=FALSE}

```

# Relación Ejecutivo - Legislativo
## Número de iniciativas gubernamentales por cuatrienio
```{r warning=FALSE, echo=FALSE, comment=FALSE, message=FALSE}
proyecto_leys   %>% 
  left_join(iniciativa %>%
              select(iniciativa_id= id, iniciativa = nombre) ) %>% 
  mutate(fecha = floor_date(fecha_radicacion, unit = "year"),
    iniciativa2  = case_when(iniciativa %in% c("Gubernamental", "Mixta")~ "Ministros", 
                                  T~"Otros")) %>%  
  count(iniciativa2,  fecha)  %>% 
  # gather(tipo, grupo, iniciativa2:iniciativa) %>% 
  hchart(hcaes(x = fecha, y = n, group =iniciativa2),type = "line") 

```
