---
title: "historico"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = F, 
message = F,
warning = F, 
fig.asp = 0.8, 
fig.width = 7, 
out.width = "100%",
dpi = 300,
collapse = TRUE,
comment = "#>"
) 
```


```{r, include = FALSE}
library(pacman)
p_load(tidyverse, magrittr, highcharter, lubridate, devtools, viridis, hrbrthemes, mapdata, here)
library(ggchicklet)
library(randomNames)

```

```{r, include = FALSE}
source(here("Gráficas", "tema.R"))
proyecto <- read_csv(here("Para Jesús", "proyecto_leys.csv"))

iniciativas <- read_csv(here("Para Jesús", "iniciativas.csv")) %>% 
               select(id, nombre) %>% 
               rename("iniciativa"="nombre")
tipo_proyecto <- read_csv(here("Para Jesús", "tipo_proyectos.csv")) %>% 
               select(id, nombre)%>% 
               rename("tipo_proyecto"="nombre")
legis <- read_csv(here("Para Jesús", "legislaturas.csv")) %>% 
               select(id:fechaFin) %>% 
               rename("legislatura"="nombre")
corpo <- read_csv(here("Para Jesús", "corporacions.csv")) %>% 
               select(id, nombre)%>% 
               rename("corporacion"="nombre")
proyecto_estado <- read_csv(here("Para Jesús", "proyecto_ley_estados.csv")) %>% 
                   select(proyecto_ley_id, estado_proyecto_ley_id, fecha)
estado_proyecto <- read_csv(here("Para Jesús", "estado_proyecto_leys.csv")) %>% 
                   select(id, nombre) %>% 
                   rename("estado_proyecto"="nombre")
estado_final <- left_join(proyecto_estado, estado_proyecto, by=c("estado_proyecto_ley_id"="id")) %>% 
                select(fecha, proyecto_ley_id, estado_proyecto) %>% 
                group_by(proyecto_ley_id) %>% 
                filter(fecha==max(fecha)) %>% 
                ungroup()

temas <- read_csv(here("Para Jesús", "temas.csv")) %>% 
         select(id, tema=nombre)

cuatri <- read_csv(here("Para Jesús", "cuatrienios.csv")) %>% 
          select(id, fecha_inicio_cuatri=fecha_inicio)

proyecto_final <- left_join(proyecto, iniciativas, by=c("iniciativa_id"="id"))

proyecto_final <- left_join(proyecto_final, tipo_proyecto, by=c("tipo_proyecto_id"="id"))

proyecto_final <- left_join(proyecto_final, legis, by=c("legislatura_id"="id"))

proyecto_final <- left_join(proyecto_final, corpo, by=c("corporacion_id"="id"))

proyecto_final <- inner_join(proyecto_final, estado_final, by=c("id" ="proyecto_ley_id"))

proyecto_final <- left_join(proyecto_final, temas, by=c("tema_id_principal" ="id"))

proyecto_final <- left_join(proyecto_final, cuatri, by=c("cuatrienio_id" ="id"))



```


```{r}

temas_prueba <- proyecto_final %>% 
                count(tema) %>% 
                arrange(desc(n))
       
temas_prueba <- temas_prueba[1:10,]
tema_vec <- temas_prueba$tema

temas <- proyecto_final %>% 
         filter(tema %in% tema_vec) %>% 
         count(fecha_inicio_cuatri, tema) %>% 
         group_by(fecha_inicio_cuatri) %>% 
         mutate(totales=sum(n, na.rm=T)) %>% 
         ungroup() %>% 
         mutate(porc=round((n/totales)*100, 2))

temas %>% 
  hchart(hcaes(x = fecha_inicio_cuatri, y =porc, group= tema), type = "area") %>%
  hc_plotOptions(area = list(stacking = T)) %>% 
      hc_add_theme(thm) %>%  
  hc_xAxis(title = list(text = "")) %>%
  hc_yAxis(title = list(text = "Porcentaje"))%>%
  hc_tooltip(pointFormat = 'Total: <b>{point.n}</b><br/>Porcentaje:  <b>{point.porc}</b>')



```



```{r}

  temas %>% 
  filter(fecha_inicio_cuatri==max(fecha_inicio_cuatri)) %>% 
  hchart(hcaes(x = tema,  value = porc), type = "treemap")%>%
  hc_title(text = "Temas de los proyectos en el cuatrienio")%>%
  hc_add_theme(thm)%>%
  hc_tooltip(pointFormat = 'Total: <b>{point.n}</b><br/>Porcentaje:  <b>{point.porc}</b>')

```




```{r}
sancionados <- proyecto_final %>% 
               filter(estado_proyecto=="Sancionado como Ley") %>%
               mutate(fecha=substr(fecha_inicio_cuatri,1,4)) %>% 
               count(fecha)
sancionados %>%
  hchart(hcaes(x = fecha, y = n), type = "line") %>%
  hc_plotOptions(line= list(lineWidth = 4,
                            marker = list(radius =0),
                            stickyTracking=F)) %>%
    hc_chart(style = list(fontFamily = "Avenir next"), polar = T) %>% 
    hc_add_theme(thm) %>% 
  hc_tooltip(
    borderWidth= 0,
    outside = T,
    textOutline= "3px contrast",
    shadow=F,
    shared = T,
    split = F,
    headerFormat= '<span style="font-size: 20px">{point.key}</span><br/>',
    pointFormat = '{point.n}'  ) %>% 
  hc_xAxis(crosshair = T, title = list(text = ""),
           lineWidth = 0, tickWidth  = 0, gridLineWidth =0,
           showLastLabel= T,
           labels = list(step = 1, style = list(fontSize = "16px", color = "#001c44") )) %>% 
  hc_yAxis(crosshair = T, title = list(text = ""), tickAmount = 3,
           dashStyle = "dot",
           gridLineWidth =.5, showFirstLabel = T,
           labels = list( style = list(fontSize = "12px") )) %>% 
  hc_title(text = "Total de Proyectos de Ley sancionados por año")

  # hc_colors(colors = c("#1A535C", "#FFE66D")) %>%






```

```{r}

proyecto_estado <- read_csv(here("Para Jesús", "proyecto_ley_estados.csv")) %>% 
                   select(proyecto_ley_id, estado_proyecto_ley_id, fecha)
estado_proyecto <- read_csv(here("Para Jesús", "estado_proyecto_leys.csv")) %>% 
                   select(id, nombre) %>% 
                   rename("estado_proyecto"="nombre")
estado_final <- left_join(proyecto_estado, estado_proyecto, by=c("estado_proyecto_ley_id"="id")) %>% 
                filter(estado_proyecto=="Sancionado como Ley") %>% 
                rename("fecha_aproba"="fecha")
proyecto <- read_csv(here("Para Jesús", "proyecto_leys.csv")) %>% 
            select(id, tipo_proyecto_id, cuatrienio_id, fecha_radicacion) %>% 
            left_join(tipo_proyecto, by=c("tipo_proyecto_id"="id")) %>% 
            left_join(estado_final, by=c("id"="proyecto_ley_id")) %>% 
            filter(!is.na(estado_proyecto)) %>% 
            unique() %>% 
            mutate(dif=fecha_aproba-fecha_radicacion, 
                   dif=as.numeric(dif))
aux <-  data_to_boxplot(data = proyecto  ,
                         variable = dif, group_var =cuatrienio_id, group_var2 = tipo_proyecto)

highchart() %>%
  hc_xAxis(type = "category") %>%
  hc_add_series_list(aux)  %>%
  hc_title(text = "Tiempo de sanción de Proyectos de Ley") %>%
  hc_xAxis(title = list(text = "Cuatrienio")) %>%
  hc_yAxis(title = list(text = "Días"), tickAmount = 6, min=0) %>%
  hc_plotOptions(series = list(showInLegend = T)) %>% 
  # hc_chart(inverted = T, zoomType = "x") %>%
  hc_tooltip(shared= F,
             pointFormat= '<span style="color:{point.color}">●</span> <b> {series.name}</b><br/>Máximo: {point.high}<br/>3º cuantil: {point.q3}<br/>Mediana: {point.median}<br/>1º cuantil: {point.q1}<br/>Mínimo: {point.low}<br/>') %>%
  hc_add_theme( thm)




```


