---
title: "queries_historico"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = F, 
                      message = F,
                      warning = F, 
                      fig.asp = 0.8, 
                      fig.width = 7, 
                      out.width = "100%",
                      dpi = 300,
                      collapse = TRUE,
                      comment = "#>"
) 
```

```{r, include = FALSE}
library(DBI)
library(tidyverse)
library(RMySQL)
library(highcharter)
library(here)
con <- dbConnect(
  drv = RMariaDB::MariaDB(),
  dbname = "prueba33_congresovisible",
  host = "162.241.62.202",
  username = "prueba33_cv_user",
  password = "CongresoVisible2020",
  port = 3306, timeout = 200, timezone = "America/Mexico_City"
)

```


```{r, include = FALSE}
#bases 

source(here("Gráficas", "tema.R"))
proyecto <- read_csv(here("Para Jesús", "proyecto_leys.csv"))

iniciativas <- read_csv(here("Para Jesús", "iniciativas.csv")) %>% 
  select(id, iniciativa = nombre) 

tipo_proyecto <- read_csv(here("Para Jesús", "tipo_proyectos.csv")) %>% 
  select(id, tipo_proyecto = nombre)

legis <- read_csv(here("Para Jesús", "legislaturas.csv")) %>% 
  select(id:cuatrienio_id, legislatura = nombre) 

corpo <- read_csv(here("Para Jesús", "corporacions.csv")) %>% 
  select(id, corporacion = nombre)

proyecto_estado <- read_csv(here("Para Jesús", "proyecto_ley_estados.csv")) %>% 
  select(proyecto_ley_id, estado_proyecto_ley_id, fecha)

estado_proyecto <- read_csv(here("Para Jesús", "estado_proyecto_leys.csv")) %>% 
  select(id, estado_proyecto = nombre) 

estado_final <- left_join(proyecto_estado, estado_proyecto, by=c("estado_proyecto_ley_id"="id")) %>% 
  select(fecha, proyecto_ley_id, estado_proyecto) %>% 
  group_by(proyecto_ley_id) %>% 
  filter(fecha==max(fecha)) %>% 
  ungroup()

temas <- read_csv(here("Para Jesús", "temas.csv")) %>% 
  select(id, tema=nombre)

cuatri <- read_csv(here("Para Jesús", "cuatrienios.csv")) %>%
  select(cuatrienio_id = id, fecha_inicio_cuatri=fecha_inicio) %>%
  arrange(fecha_inicio_cuatri) %>% mutate(cuatrienio=row_number(),
                                          cuatrienio=factor(cuatrienio, labels = c("1994-1998", "1998-2002",
                                                                                   "2002-2006", "2006-2010", "2010-2014", "2014-2018",
                                                                                   "2018-2022")))

proyecto_final <- left_join(proyecto, iniciativas, by=c("iniciativa_id"="id"))

proyecto_final <- left_join(proyecto_final, tipo_proyecto, by=c("tipo_proyecto_id"="id"))

proyecto_final <- left_join(proyecto_final, legis, by=c("legislatura_id"="id", "cuatrienio_id"))

proyecto_final <- left_join(proyecto_final, corpo, by=c("corporacion_id"="id"))

proyecto_final <- inner_join(proyecto_final, estado_final, by=c("id" ="proyecto_ley_id"))

proyecto_final <- left_join(proyecto_final, temas, by=c("tema_id_principal" ="id"))

proyecto_final <- left_join(proyecto_final, cuatri, by="cuatrienio_id")


congresistas <- read_csv(here("Para Jesús/congresistas.csv"))
partidos <- read_csv("Para Jesús/partidos.csv" %>%  here())
personas <- read_csv("Para Jesús/personas.csv" %>%  here())
sexo <- read_csv("Para Jesús/generos.csv" %>%  here())

control_pol_0 <- read_csv("Para Jesús/control_politico_citados.csv" %>%  here())
control_pol_1 <- read_csv("Para Jesús/control_politico_citantes.csv" %>%  here())
control_pol_2 <- read_csv("Para Jesús/control_politicos.csv"  %>% here())


```

```{r}
tbl(con, 
    "proyecto_ley_estados") %>%  
    filter(estado_proyecto_ley_id=="40") %>% 
    left_join(
    tbl(con, "proyecto_leys") %>% 
    select(id, cuatrienio_id),
    by = c("proyecto_ley_id"="id")
  )  %>% 
    left_join(
    tbl(con, "cuatrienios") %>% 
      select(cuatrienio_id = id, cuatrienio=nombre), 
    by = "cuatrienio_id" 
  )  %>% 
      left_join(
    tbl(con, "estado_proyecto_leys") %>% 
      select(estado_proyecto_ley_id = id, estado=nombre), 
    by = "estado_proyecto_ley_id" 
  )  %>% 
  filter(estado=="Sancionado como Ley") %>% 
  count(cuatrienio) %>% 
  show_query()


```

## No reacciona al filtro
```{r total-pl-comoley, echo =FALSE }


sancionados <- proyecto_final %>% 
  filter(estado_proyecto=="Sancionado como Ley") %>%
  count(cuatrienio)

sancionados %>% # Ordenar por factores la y
  hchart('bar', hcaes(x = cuatrienio, y = n)) %>%
  hc_tooltip(pointFormat = 'Total de proyectos sancionados : {point.n}')%>%
  hc_title(text = "Total de Proyectos de Ley sancionados por año") %>%
  hc_xAxis(title = list(text = "")) %>%
  hc_yAxis(title = list(text = "")) %>%
  hc_plotOptions(bar=list(borderRadius =5, colorByPoint = F))%>%
  hc_add_theme(thm)
```



```{r}
  tbl(con, "proyecto_leys") %>% 
  count(tema_id_principal) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  left_join(
    tbl(con, "proyecto_leys") %>% 
  select(id, cuatrienio_id, tema_id_principal),
    by = c("tema_id_principal")
  ) %>%
  left_join(
    tbl(con, "temas") %>% 
      select(tema_id_principal=id, tema=nombre),
    by = c("tema_id_principal")
  ) %>% 
  left_join(
    tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id = id, cuatrienio=nombre), 
    by = "cuatrienio_id" 
  ) %>% 
  count(cuatrienio, tema) %>% 
  filter(n!=1) %>% 
  show_query()


```


## No reacciona al filtro
```{r temas-recurrentes, echo =FALSE}

temas_prueba <- proyecto_final %>% 
  count(tema) %>% 
  arrange(desc(n))

temas_prueba <- temas_prueba[1:10,]
tema_vec <- temas_prueba$tema

temas <- proyecto_final %>% 
  filter(tema %in% tema_vec) %>% 
  count(fecha_inicio_cuatri, tema) %>% 
  group_by(fecha_inicio_cuatri) %>% 
  mutate(totales=sum(n, na.rm=T)) %>% 
  ungroup() %>% 
  mutate(porc=round((n/totales)*100)) %>% 
  filter(fecha_inicio_cuatri!="1994-07-20")

temas %>% 
  hchart(hcaes(x = fecha_inicio_cuatri, y =porc, group= tema), type = "area") %>%
  hc_plotOptions(area = list(stacking = T)) %>% 
  hc_add_theme(thm) %>%  
  hc_xAxis(title = list(text = ""), crosshair = T) %>%
  hc_yAxis(title = list(text = "Porcentaje"))%>%
  hc_tooltip(pointFormat = '{point.tema}: <b>{point.n} </b> <b> ({point.porc}%)</b><br>',
             shared = T)

```


```{r}
  tbl(con, "proyecto_leys") %>% 
  count(tema_id_principal) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  left_join(
    tbl(con, "proyecto_leys") %>% 
  select(id, cuatrienio_id, tema_id_principal),
    by = c("tema_id_principal")
  ) %>%
  left_join(
    tbl(con, "temas") %>% 
      select(tema_id_principal=id, tema=nombre),
    by = c("tema_id_principal")
  ) %>% 
  left_join(
    tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id = id, cuatrienio=nombre), 
    by = "cuatrienio_id" 
  ) %>% 
  count(cuatrienio, tema) %>% 
  filter(n!=1) %>% 
  filter(cuatrienio=="2018-2022") %>% 
  show_query()


```



## Sí reacciona al filtro
```{r temas-recurrentes-2, echo =FALSE}

temas %>% 
  filter(fecha_inicio_cuatri==max(fecha_inicio_cuatri)) %>% 
  mutate(tema=paste(tema, paste0(porc, "%"), sep="\n")) %>% 
  hchart(hcaes(x = tema,  value = porc), type = "treemap")%>%
  hc_title(text = "Temas de los proyectos en el cuatrienio 2008")%>%
  hc_add_theme(thm)%>%
  hc_tooltip(pointFormat = 'Total: <b>{point.n}</b> <b> ({point.porc})%</b>') %>% 
  hc_plotOptions(series = list(colorByPoint =T)) 

```




```{r}
tbl(con, 
    "proyecto_ley_estados") %>%  
    filter(estado_proyecto_ley_id=="40") %>% 
  left_join(
  tbl(con, "estado_proyecto_leys") %>% 
  select(estado_proyecto_ley_id = id, estado=nombre), 
  by = "estado_proyecto_ley_id" 
  ) %>% 
  inner_join(
    tbl(con, "proyecto_leys") %>% 
    select(id, cuatrienio_id, tipo_proyecto_id, fecha_radicacion),
    by = c("proyecto_ley_id"="id")
  )  %>% 
    left_join(
    tbl(con, "tipo_proyectos") %>% 
      select(tipo_proyecto_id = id, proyecto=nombre), 
    by = "tipo_proyecto_id" 
  )  %>% 
    left_join(
    tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id = id, cuatrienio=nombre), 
    by = "cuatrienio_id" 
  ) %>% 
  mutate(dif=DATEDIFF(fecha,fecha_radicacion),
         variable_deborah=round(dif/365, 2)) %>% 
show_query()


```
## No reacciona al filtro
```{r tiempo-sansionley, echo =FALSE}
#PENDIENTE
proyecto_estado <- read_csv(here("Para Jesús", "proyecto_ley_estados.csv")) %>% 
  select(proyecto_ley_id, estado_proyecto_ley_id, fecha)
estado_proyecto <- read_csv(here("Para Jesús", "estado_proyecto_leys.csv")) %>% 
  select(id, nombre) %>% 
  rename("estado_proyecto"="nombre")
estado_final <- left_join(proyecto_estado, estado_proyecto, by=c("estado_proyecto_ley_id"="id")) %>% 
  filter(estado_proyecto=="Sancionado como Ley") %>% 
  rename("fecha_aproba"="fecha")

proyecto <- read_csv(here("Para Jesús", "proyecto_leys.csv")) %>% 
  select(id, tipo_proyecto_id, cuatrienio_id, fecha_radicacion) %>% 
  left_join(tipo_proyecto, by=c("tipo_proyecto_id"="id")) %>% 
  left_join(estado_final, by=c("id"="proyecto_ley_id")) %>% 
  left_join(cuatri, by="cuatrienio_id") %>% 
  filter(!is.na(estado_proyecto)) %>% 
  unique() %>% 
  mutate(dif=fecha_aproba-fecha_radicacion, 
         dif=as.numeric(dif))
aux <-  data_to_boxplot(data = proyecto  ,
                        variable = dif, group_var =cuatrienio, group_var2 = tipo_proyecto)

highchart() %>%
  hc_xAxis(type = "category") %>%
  hc_add_series_list(aux)  %>%
  hc_title(text = "Tiempo de sanción de Proyectos de Ley") %>%
  hc_xAxis(title = list(text = "Cuatrienio")) %>%
  hc_yAxis(title = list(text = "Días"), tickAmount = 6, min=0) %>%
  hc_plotOptions(series = list(showInLegend = T)) %>% 
  # hc_chart(inverted = T, zoomType = "x") %>%
  hc_tooltip(shared= F,
             pointFormat= '<span style="color:{point.color}">●</span> <b> {series.name}</b><br/>Máximo: {point.high}<br/>3º cuantil: {point.q3}<br/>Mediana: {point.median}<br/>1º cuantil: {point.q1}<br/>Mínimo: {point.low}<br/>') %>%
  hc_add_theme( thm) %>%  hc_chart(inverted= T)%>% 
  hc_colors(c("#0B3B5D", "#17789E"))

```




```{r}

 tbl(con, "congresistas") %>% 
 select(congresista_id = id, persona_id, cuatrienio_id, partido_id) %>%
  left_join(
      tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id=id, fechaInicio),
      by = c("cuatrienio_id")
    ) %>% 
  left_join(
    tbl(con, "partidos") %>%  select(partido_id =id,partido  = nombre, color),
    by = "partido_id" 
  ) %>% 
  left_join(
    tbl(con, "personas") %>%  select(persona_id = id, genero_id),
    by = c("persona_id")
  ) %>% 
    left_join(
    tbl(con, "generos") %>%  select(genero_id = id, genero = nombre),
            by = "genero_id"
  )  %>% 
  filter(!is.na(genero)) %>% 
  count(fechaInicio, genero) %>% 
  show_query()
  
  

```


## No reacciona al filtro

```{r proporcion-mujeres-1, echo =FALSE}

aux <- congresistas %>% select(congresista_id = id, persona_id, cuatrienio_id, partido_id) %>%
  left_join(cuatri %>%
              select(cuatrienio_id, fechaInicio=fecha_inicio_cuatri),
            by = "cuatrienio_id") %>%
  left_join(partidos %>%
              select(partido_id =id, partido  = nombre, color),
            by = "partido_id" ) %>%
  left_join(personas %>%
              select(persona_id = id, genero_id),
            by = "persona_id") %>%
  left_join(sexo %>%
              select(genero_id = id, genero = nombre),
            by = "genero_id") %>%
  filter(!is.na(genero)) %>% 
  group_by(fechaInicio, genero) %>%
  summarise(n = n())%>%
  mutate(pct = round(100*n / sum(n), 1))

aux %>%
  hchart(hcaes(x = 'fechaInicio', group = 'genero', y = 'pct'), type = "area") %>%
  hc_plotOptions(area = list(stacking = T)) %>%
  hc_title(text = "Proporción de mujeres") %>%
  hc_subtitle(text = "Historico") %>%
  hc_tooltip(pointFormat = '{series.name}: {point.pct} %<br>') %>%
  hc_xAxis(title = list(text = "Fecha cuatrienios"), crosshair =T,
           labels = list(step= 2)) %>%
  hc_yAxis(title = list(text = "Porcentaje"),
           min=0) %>%
  hc_add_theme(thm)%>% 
  hc_tooltip(shared = T) %>% 
  hc_colors(c("#0B3B5D", "#17789E"))
```


```{r}

 tbl(con, "congresistas") %>% 
 select(congresista_id = id, persona_id, cuatrienio_id, partido_id) %>%
  left_join(
      tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id=id, fechaInicio, cuatrienio=nombre),
      by = c("cuatrienio_id")
    ) %>% 
  left_join(
    tbl(con, "partidos") %>%  select(partido_id =id,partido  = nombre, color),
    by = "partido_id" 
  ) %>% 
  left_join(
    tbl(con, "personas") %>%  select(persona_id = id, genero_id),
    by = c("persona_id")
  ) %>% 
    left_join(
    tbl(con, "generos") %>%  select(genero_id = id, genero = nombre),
            by = "genero_id"
  )  %>% 
  filter(!is.na(genero), cuatrienio=="2018-2022") %>% 
  count(genero, partido)%>% 
  show_query()
  
  

```



## Sí reacciona al filtro
```{r proporcion-mujeres-2, echo =FALSE}
# Por cuatrienio
id <- 1
aux <- congresistas %>% select(congresista_id = id, persona_id, cuatrienio_id, partido_id) %>% 
  left_join(partidos %>%
              select(partido_id =id, partido  = nombre),
            by = "partido_id" ) %>%
  left_join(personas %>%
              select(persona_id = id, genero_id),
            by = "persona_id") %>%
  left_join(sexo %>%
              select(genero_id = id, genero = nombre),
            by = "genero_id") %>%
  left_join(cuatri, by = "cuatrienio_id") %>%
  filter(!is.na(genero), cuatrienio_id == id) 


base1 <- aux %>%
  select(partido) %>%
  unique()

base1 <- base1 %>%
  mutate(id = str_to_id(partido)) %>%
  bind_cols(tibble(color = hcl.colors(nrow(base1), palette = "viridis"))) %>%
  rename("name" = "partido")

base2 <- aux %>%
  count(genero, partido) %>%
  mutate(color = if_else(genero == "Masculino", "#17789e",
                         if_else(genero == "Femenino","#66CCFF","#808080")),
         parent=str_to_id(partido),
         id = as.character(row_number())) %>%
  rename("name"= "genero", "value"="n") %>% 
  mutate(partido=if_else(value<5," ", partido)) 


dde <- list(base1, base2) %>%
  purrr::map(mutate_if, is.factor, as.character) %>%
  bind_rows() %>%
  list_parse() %>%
  purrr::map(function(x) x[!is.na(x)])


highchart() %>%
  hc_chart(type = "treemap") %>%
  hc_add_series(
    data = dde, allowDrillToNode = TRUE,
    levelIsConstant = TRUE, textOverflow = "clip",
    dataLabels = list(color = "white"),
    levels = list(
      list(level = 1, borderWidth = 1,
           dataLabels = list(enabled = F, verticalAlign = "top",
                             align = "left", style = list(fontSize = "12px", textOutline = FALSE)) ),
      list(level = 2, borderWidth = 0, dataLabels = list(enabled = FALSE))
    )) %>% 
  hc_title(text = "Proporción de mujeres") %>%
  hc_add_theme(thm)%>%
  hc_colors("transparent") 


```


```{r}

 tbl(con, "proyecto_leys") %>% 
  left_join(
      tbl(con, "iniciativas") %>%  
      select(iniciativa_id=id, iniciativa=nombre),
      by = c("iniciativa_id")
    ) %>% 
  left_join(
      tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id=id, cuatrienio=nombre),
      by = c("cuatrienio_id")
    )%>% 
 filter(iniciativa=="Gubernamental") %>% 
  count(cuatrienio, iniciativa)%>% 
  show_query()
  
  

```


## No reacciona al filtro
```{r  numero-iniciativas, echo =FALSE}
# Número de iniciativas gubernamentales por cuatrienio  ---------------------------------------

aux <- proyecto_final %>%
  group_by(cuatrienio) %>% 
  summarise(n = n()) 

aux %>% # Ordenar por factores la y
  hchart('bar', hcaes(x = 'cuatrienio', y = n)) %>%
  hc_title(text = "Número de iniciativas gubernamentales") %>%
  hc_xAxis(title = list(text = "")) %>%
  hc_yAxis(title = list(text = "")) %>%
  hc_plotOptions(bar=list(borderRadius =10), series = list(showInLegend = F)) %>% 
  hc_add_theme(thm) %>% 
  hc_tooltip(pointFormat = '{point.n} iniciativas')




```

```{r}

 tbl(con, "congresistas") %>% 
  left_join(
      tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id=id, cuatrienio=nombre),
      by = c("cuatrienio_id")
    ) %>% 
  left_join(
    tbl(con, "partidos") %>%  select(partido_id =id,partido  = nombre, color),
    by = "partido_id" 
  ) %>% 
  left_join(
    tbl(con, "personas") %>%  select(persona_id = id, nombres, apellidos, genero_id, fechaNacimiento),
    by = c("persona_id")
  ) %>%
  mutate(edad =round(DATEDIFF(CURDATE(),fechaNacimiento)/365)) %>% 
  group_by(partido, cuatrienio) %>%
  summarise(mediana=mean(edad, na.rm=T)) %>% 
  ungroup() %>% 
  filter(cuatrienio=="1998-2002") %>% 
  arrange(desc(mediana)) %>% 
  head(10) %>% 
  show_query()
         
```        
## Sí reacciona al filtro

```{r edad-partidista-old, echo =FALSE}
# edad - composición partidista
congresistas <- read_csv(here("Para Jesús", "congresistas.csv"))
partidos <- read_csv(here("Para Jesús", "partidos.csv"))
personas <- read_csv(here("Para Jesús", "personas.csv")) %>% 
  filter(!is.na(fechaNacimiento)) 

personas$dia <- substr(personas$fechaNacimiento, 1,2)
personas$mes <- substr(personas$fechaNacimiento, 4,5)
personas$year <- substr(personas$fechaNacimiento, 7,8)
personas$year_ <- paste0("19", personas$year)
personas$nacim <- paste(personas$year_, personas$mes, personas$dia, sep="/")


aux <- congresistas %>% 
  select(congresista_id = id, persona_id, cuatrienio_id, partido_id) %>%
  left_join(partidos %>%
              select(partido_id =id, partido  = nombre, color),
            by = "partido_id" ) %>%
  left_join(personas %>%
              select(persona_id = id, nacim),
            by = "persona_id") %>%
  left_join(cuatri, by="cuatrienio_id") %>% 
  filter(!is.na(nacim)) %>%
  mutate(nacim = lubridate::ymd(nacim), 
         edad =round(as.numeric(fecha_inicio_cuatri- nacim)/365, 0)) 


barras <- aux %>%
  group_by(partido) %>%
  summarise(mediana=median(edad)) %>% 
  ungroup() %>% 
  arrange(desc(mediana))

barras_viejos <- barras %>% 
  arrange(desc(mediana))

barras_viejos <- barras_viejos[1:10,]

barras_viejos %>%  hchart(hcaes(y = mediana, x = partido), type = "bar") %>%
  hc_title(text = "Top 5 partidos con congresitas de mayor edad") %>%
  hc_xAxis(title = list(text = " ")) %>%
  hc_yAxis(title = list(text = "Mediana de edad")) %>%
  hc_tooltip(shared = T,
             pointFormat = '<br/>Mediana de edad:  <b>{point.mediana}</b>') %>%
  hc_add_theme( thm)%>% 
  hc_plotOptions(bar=list(borderRadius =5, colorByPoint = T))


```

```{r}

 tbl(con, "congresistas") %>% 
  left_join(
      tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id=id, cuatrienio=nombre),
      by = c("cuatrienio_id")
    ) %>% 
  left_join(
    tbl(con, "partidos") %>%  select(partido_id =id,partido  = nombre, color),
    by = "partido_id" 
  ) %>% 
  left_join(
    tbl(con, "personas") %>%  select(persona_id = id, nombres, apellidos, genero_id, fechaNacimiento),
    by = c("persona_id")
  ) %>%
  mutate(edad =round(DATEDIFF(CURDATE(),fechaNacimiento)/365)) %>% 
  group_by(partido, cuatrienio) %>%
  summarise(mediana=mean(edad, na.rm=T)) %>% 
  ungroup() %>% 
  filter(!is.na(mediana)) %>% 
  filter(cuatrienio=="1998-2002") %>% 
  arrange(mediana) %>% 
  head(10) %>% 
  show_query()
         
```  
## Sí reacciona al filtro

```{r edad-partidista-young, echo =FALSE}

barras_jov <- barras %>% 
  arrange(mediana)

barras_jov <- barras_jov[1:10,]


barras_jov %>%  hchart(hcaes(y = mediana, x = partido), type = "bar") %>%
  hc_title(text = "Top 5 partidos con congresitas más jóvenes") %>%
  hc_xAxis(title = list(text = " ")) %>%
  hc_yAxis(title = list(text = "Mediana de edad")) %>%
  hc_tooltip(shared = T,
             pointFormat = '<br/>Mediana de edad:  <b>{point.mediana}</b>') %>%
  hc_add_theme( thm)%>% 
  hc_plotOptions(bar=list(borderRadius =5, colorByPoint = T))

```

# Queries para gráfica distribución de edad (6)
## No reacciona al filtro


```{r}

cuat1<- tbl(con, "congresistas") %>% 
  left_join(
      tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id=id, cuatrienio=nombre, fechaInicio),
      by = c("cuatrienio_id")
    ) %>% 
  left_join(
    tbl(con, "partidos") %>%  select(partido_id =id,partido  = nombre, color),
    by = "partido_id" 
  ) %>% 
  left_join(
    tbl(con, "personas") %>%  select(persona_id = id, nombres, apellidos, genero_id, fechaNacimiento),
    by = c("persona_id")
  ) %>%
    filter(cuatrienio=="1998-2002", 
         !is.na(fechaNacimiento)) %>%
  mutate(fechaInicio=DATE(CONCAT(`fechaInicio`, '-07-20')),
        edad = round(DATEDIFF(fechaInicio,fechaNacimiento)/365)) %>% 
  filter(edad>=25) %>% 
        collect()

         
```  

```{r}

cuat2 <- tbl(con, "congresistas") %>% 
  left_join(
      tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id=id, cuatrienio=nombre),
      by = c("cuatrienio_id")
    ) %>% 
  left_join(
    tbl(con, "partidos") %>%  select(partido_id =id,partido  = nombre, color),
    by = "partido_id" 
  ) %>% 
  left_join(
    tbl(con, "personas") %>%  select(persona_id = id, nombres, apellidos, genero_id, fechaNacimiento),
    by = c("persona_id")
  ) %>%
  mutate(edad =round(DATEDIFF(CURDATE(),fechaNacimiento)/365)) %>% 
  filter(cuatrienio=="2002-2006", 
         !is.na(edad))%>%
  show_query()
         
``` 

```{r}

cuat3 <- tbl(con, "congresistas") %>% 
  left_join(
      tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id=id, cuatrienio=nombre),
      by = c("cuatrienio_id")
    ) %>% 
  left_join(
    tbl(con, "partidos") %>%  select(partido_id =id,partido  = nombre, color),
    by = "partido_id" 
  ) %>% 
  left_join(
    tbl(con, "personas") %>%  select(persona_id = id, nombres, apellidos, genero_id, fechaNacimiento),
    by = c("persona_id")
  ) %>%
  mutate(edad =round(DATEDIFF(CURDATE(),fechaNacimiento)/365)) %>% 
  filter(cuatrienio=="2006-2010", 
         !is.na(edad))%>%
  show_query()
         
``` 

```{r}

cuat4 <- tbl(con, "congresistas") %>% 
  left_join(
      tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id=id, cuatrienio=nombre),
      by = c("cuatrienio_id")
    ) %>% 
  left_join(
    tbl(con, "partidos") %>%  select(partido_id =id,partido  = nombre, color),
    by = "partido_id" 
  ) %>% 
  left_join(
    tbl(con, "personas") %>%  select(persona_id = id, nombres, apellidos, genero_id, fechaNacimiento),
    by = c("persona_id")
  ) %>%
  mutate(edad =round(DATEDIFF(CURDATE(),fechaNacimiento)/365)) %>% 
  filter(cuatrienio=="2010-2014", 
         !is.na(edad))%>%
  show_query()
         
``` 


```{r}

 cuat5 <- tbl(con, "congresistas") %>% 
  left_join(
      tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id=id, cuatrienio=nombre),
      by = c("cuatrienio_id")
    ) %>% 
  left_join(
    tbl(con, "partidos") %>%  select(partido_id =id,partido  = nombre, color),
    by = "partido_id" 
  ) %>% 
  left_join(
    tbl(con, "personas") %>%  select(persona_id = id, nombres, apellidos, genero_id, fechaNacimiento),
    by = c("persona_id")
  ) %>%
  mutate(edad =round(DATEDIFF(CURDATE(),fechaNacimiento)/365)) %>% 
  filter(cuatrienio=="2014-2018",
         !is.na(edad))%>%
  show_query()
         
``` 



```{r}

 cuat6 <- tbl(con, "congresistas") %>% 
  left_join(
      tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id=id, cuatrienio=nombre),
      by = c("cuatrienio_id")
    ) %>% 
  left_join(
    tbl(con, "partidos") %>%  select(partido_id =id,partido  = nombre, color),
    by = "partido_id" 
  ) %>% 
  left_join(
    tbl(con, "personas") %>%  select(persona_id = id, nombres, apellidos, genero_id, fechaNacimiento),
    by = c("persona_id")
  ) %>%
  mutate(edad =round(DATEDIFF(CURDATE(),fechaNacimiento)/365)) %>% 
  filter(cuatrienio=="2018-2022",
         !is.na(edad))%>%
  show_query()
         
``` 

## No reacciona al filtro

```{r edad-partidista-distribucion, echo =FALSE}

# c_dem <- aux %>% 
#          filter(partido=="Conservador Colombiano")

cuat1 <- aux %>% 
  filter(cuatrienio=="1998-2002")

cuat2 <- aux %>% 
  filter(cuatrienio=="2002-2006")
cuat3 <- aux %>% 
  filter(cuatrienio=="2006-2010")
cuat4 <- aux %>% 
  filter(cuatrienio=="2010-2014")
cuat5 <- aux %>% 
  filter(cuatrienio=="2014-2018")
cuat6 <- aux %>% 
  filter(cuatrienio=="2018-2022") 




hchart(
  density(cuat1$edad), 
  type = "area", 
  color = "#66CCFF", name = "1998-2002"
) %>% 
  hc_add_series(
    density(cuat2$edad), 
    type = "area", 
    color = "#17789E", name = "2002-2006"
  )%>% 
  hc_add_series(
    density(cuat3$edad), 
    type = "area", 
    color = "#6AEEB0", name = "2010-2014"
  )%>% 
  hc_add_series(
    density(cuat4$edad), 
    type = "area", 
    color = "#379E80", name = "2010-2014"
  ) %>%
  hc_title(text = "Distribución de edad en el congreso por cuatrienio") %>%
  hc_add_theme( thm)


```




```{r}

 tbl(con, "congresistas") %>% 
  left_join(
      tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id=id, cuatrienio=nombre),
      by = c("cuatrienio_id")
    ) %>% 
  left_join(
    tbl(con, "partidos") %>%  select(partido_id =id,partido  = nombre, color),
    by = "partido_id" 
  ) %>% 
  count(partido, cuatrienio)%>% 
  filter(n>=10) %>% 
  arrange(cuatrienio)%>% 
  show_query()
         
``` 
## No reacciona al filtro

```{r}

#Composición
aux <- congresistas %>% 
  select(congresista_id = id, persona_id, cuatrienio_id, partido_id) %>%
  left_join(partidos %>%
              select(partido_id =id, partido  = nombre, color),
            by = "partido_id" ) %>%
  left_join(personas %>%
              select(persona_id = id, nacim),
            by = "persona_id") %>%
  left_join(cuatri, by="cuatrienio_id") %>% 
  count(partido, cuatrienio) %>% 
  filter(n>=10) %>% 
  arrange(cuatrienio)

aux %>% 
  hchart(hcaes(from = partido, to  = cuatrienio, weight =n), type = "sankey") %>%
  hc_title(text = "Partidos con mayor representación en el Congreso, por cuatrienio")%>%
  hc_add_theme(thm) %>% 
  hc_tooltip(headerFormat = "")

```


```{r , echo =FALSE}

tbl(con, 
    "proyecto_ley_estados") %>%  
    filter(estado_proyecto_ley_id=="40") %>% 
  left_join(
  tbl(con, "estado_proyecto_leys") %>% 
  select(estado_proyecto_ley_id = id, estado=nombre), 
  by = "estado_proyecto_ley_id" 
  ) %>% 
  inner_join(
    tbl(con, "proyecto_leys") %>% 
    select(id, cuatrienio_id, iniciativa_id, fecha_radicacion),
    by = c("proyecto_ley_id"="id")
  )  %>% 
  left_join(
      tbl(con, "iniciativas") %>%  
      select(iniciativa_id=id, iniciativa=nombre),
      by = c("iniciativa_id")
    )   %>% 
    left_join(
    tbl(con, "cuatrienios") %>%  
      select(cuatrienio_id = id, cuatrienio=nombre), 
    by = "cuatrienio_id" 
  ) %>% 
  filter(iniciativa == "Gubernamental") %>% 
  count(cuatrienio) %>% 
  show_query()
```

## No reacciona al filtro

```{r iniciativas-gubernamentales-ley, echo =FALSE}


aux <- proyecto_final %>%
  filter(iniciativa == "Gubernamental", estado_proyecto == "Sancionado como Ley")  %>%
  group_by(cuatrienio) %>%
  summarise(n = n()) %>%
  na.omit()

aux %>% # Una serie de tiempo, como la línea y el punto, evolucion
  hchart('bar', hcaes(x = 'cuatrienio', y = n)) %>%
  hc_tooltip(pointFormat = 'Núm. iniciativas gubernamentales : {point.n}')%>%
  hc_title(text = "Número de iniciativas gubernamentales sancionadas como ley") %>%
  hc_xAxis(title = list(text = "")) %>%
  hc_yAxis(title = list(text = "")) %>%
  hc_plotOptions(bar=list(borderRadius =5, colorByPoint = F))%>%
  hc_add_theme(thm)

# Highcharts, area de gradado
# Gubernamental vs no gubernamental, treemap, lineas de votos a favor, separadas por tipo de iniativa,
# Sankey, dos divisiones a favor o encontra, corte a favor en contra
# Heatmap particosvs cuatrienio, porcentaje favorable(z)

```


