---
title: "queries_congreso_hoy"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = F, 
                      message = F,
                      warning = F, 
                      fig.asp = 0.8, 
                      fig.width = 7, 
                      out.width = "100%",
                      dpi = 300,
                      collapse = TRUE,
                      comment = "#>"
) 
```

```{r, include = FALSE}
library(DBI)
library(tidyverse)
library(RMySQL)
library(highcharter)
library(here)
con <- dbConnect(
  drv = RMariaDB::MariaDB(),
  dbname = "prueba33_congresovisible",
  host = "162.241.62.202",
  username = "prueba33_cv_user",
  password = "CongresoVisible2020",
  port = 3306, timeout = 200, timezone = "America/Mexico_City"
)

dbListTables(con) 

tbl(con, "proyecto_leys") %>% view()
tbl(con, "corporacions") %>% view()
```



```{r, include = FALSE}
#bases

source(here("Gráficas", "tema.R"))
proyecto <- read_csv(here("Para Jesús", "proyecto_leys.csv"))

iniciativas <- read_csv(here("Para Jesús", "iniciativas.csv")) %>% 
  select(id, iniciativa = nombre) 

tipo_proyecto <- read_csv(here("Para Jesús", "tipo_proyectos.csv")) %>% 
  select(id, tipo_proyecto = nombre)

legis <- read_csv(here("Para Jesús", "legislaturas.csv")) %>% 
  select(id:cuatrienio_id, legislatura = nombre) 

corpo <- read_csv(here("Para Jesús", "corporacions.csv")) %>% 
  select(id, corporacion = nombre)

proyecto_estado <- read_csv(here("Para Jesús", "proyecto_ley_estados.csv")) %>% 
  select(proyecto_ley_id, estado_proyecto_ley_id, fecha)

estado_proyecto <- read_csv(here("Para Jesús", "estado_proyecto_leys.csv")) %>% 
  select(id, estado_proyecto = nombre) 

estado_final <- left_join(proyecto_estado, estado_proyecto, by=c("estado_proyecto_ley_id"="id")) %>% 
  select(fecha, proyecto_ley_id, estado_proyecto) %>% 
  group_by(proyecto_ley_id) %>% 
  filter(fecha==max(fecha)) %>% 
  ungroup()

temas <- read_csv(here("Para Jesús", "temas.csv")) %>% 
  select(id, tema=nombre)

cuatri <- read_csv(here("Para Jesús", "cuatrienios.csv")) %>%
  select(cuatrienio_id = id, fecha_inicio_cuatri=fecha_inicio) %>%
  arrange(fecha_inicio_cuatri) %>% mutate(cuatrienio=row_number(),
                                          cuatrienio=factor(cuatrienio, labels = c("1994-1998", "1998-2002",
                                                                                   "2002-2006", "2006-2010", "2010-2014", "2014-2018",
                                                                                   "2018-2022")))

proyecto_final <- left_join(proyecto, iniciativas, by=c("iniciativa_id"="id"))

proyecto_final <- left_join(proyecto_final, tipo_proyecto, by=c("tipo_proyecto_id"="id"))

proyecto_final <- left_join(proyecto_final, legis, by=c("legislatura_id"="id", "cuatrienio_id"))

proyecto_final <- left_join(proyecto_final, corpo, by=c("corporacion_id"="id"))

proyecto_final <- inner_join(proyecto_final, estado_final, by=c("id" ="proyecto_ley_id"))

proyecto_final <- left_join(proyecto_final, temas, by=c("tema_id_principal" ="id"))

proyecto_final <- left_join(proyecto_final, cuatri, by="cuatrienio_id")


congresistas <- read_csv(here("Para Jesús/congresistas.csv"))
partidos <- read_csv("Para Jesús/partidos.csv" %>%  here())
personas <- read_csv("Para Jesús/personas.csv" %>%  here())
sexo <- read_csv("Para Jesús/generos.csv" %>%  here())

control_pol_0 <- read_csv("Para Jesús/control_politico_citados.csv" %>%  here())
control_pol_1 <- read_csv("Para Jesús/control_politico_citantes.csv" %>%  here())
control_pol_2 <- read_csv("Para Jesús/control_politicos.csv"  %>% here())
```

```{r}

 tbl(con, "proyecto_leys") %>% left_join(
  tbl(con, "legislaturas") %>% select(id, fechaInicio), 
  by = c("legislatura_id" = "id")) %>%  
    left_join(
      tbl(con, "corporacions") %>%  select(id, corporacion = nombre),
      by = c("corporacion_id" = "id")
    ) %>% 
  left_join(
    tbl(con, "temas") %>%  select(id, iniciativa = nombre),
    by = c("iniciativa_id" = "id")
  ) %>% 
  left_join(
    tbl(con, "tipo_proyectos") %>%  select(id, tipo_proyecto = nombre),
    by = c("tipo_proyecto_id" = "id")
  ) %>% 
  filter(tipo_proyecto=="Proyecto de Ley" & corporacion=="Senado de la República" & legislatura_id==27) %>% 
   count(tipo_proyecto, iniciativa) %>% 
   arrange(desc(n)) %>% show_query()


```


```{r}
proyecto_final_senado <- proyecto_final %>% 
                         filter(legislatura_id==max(legislatura_id) & corporacion=="Senado" & tipo_proyecto=="Proyecto de Ley")  %>% 
                         count(tipo_proyecto, iniciativa) %>% 
                         arrange(desc(n))


  proyecto_final_senado %>% 
  hchart(hcaes(x = iniciativa, y = n), type = "bar") %>% 
  hc_title(text = "Origen de las iniciativas en el Senado")%>%
  
  hc_add_theme(thm) %>% 
  hc_xAxis(title = list(text = "Iniciativa")) %>%
  hc_yAxis(title = list(text = "Total")) %>% 
 hc_plotOptions(bar=list(borderRadius =5, colorByPoint = T))%>%
  hc_tooltip(pointFormat = '<b>{point.n}</b>')


```

```{r}

 tbl(con, "proyecto_leys") %>% left_join(
  tbl(con, "legislaturas") %>% select(id, fechaInicio), 
  by = c("legislatura_id" = "id")) %>%  
    left_join(
      tbl(con, "corporacions") %>%  select(id, corporacion = nombre),
      by = c("corporacion_id" = "id")
    ) %>% 
  left_join(
    tbl(con, "iniciativas") %>%  select(id, iniciativa = nombre),
    by = c("iniciativa_id" = "id")
  ) %>% 
  left_join(
    tbl(con, "tipo_proyectos") %>%  select(id, tipo_proyecto = nombre),
    by = c("tipo_proyecto_id" = "id")
  ) %>% 
  filter(tipo_proyecto=="Proyecto de Ley" & corporacion!="Senado de la República" & legislatura_id==27) %>% 
   count(tipo_proyecto, iniciativa) %>% 
   arrange(desc(n)) %>% show_query()


```

```{r}

proyecto_final_camara <- proyecto_final %>% 
                         filter(legislatura_id==max(legislatura_id) & corporacion!="Senado"& tipo_proyecto=="Proyecto de Ley") %>% 
                         count(tipo_proyecto, iniciativa) %>% 
                         arrange(desc(n))



  proyecto_final_camara %>% 
  hchart(hcaes(x = iniciativa, y = n), type = "bar") %>% 
  hc_title(text = "Origen de las iniciativas en la Cámara de Representantes")%>%
  hc_add_theme(thm)%>% 
  hc_xAxis(title = list(text = "Iniciativa")) %>%
  hc_yAxis(title = list(text = "Total"), tickAmount = 6)%>% 
 hc_plotOptions(bar=list(borderRadius =5, colorByPoint = T))%>%
  hc_tooltip(pointFormat = '<b>{point.n}</b> ')


```
```{r}
tbl(con, "proyecto_leys") %>% left_join(
  tbl(con, "legislaturas") %>% select(id, fechaInicio), 
  by = c("legislatura_id" = "id")) %>%  
    left_join(
      tbl(con, "corporacions") %>%  select(id, corporacion = nombre),
      by = c("corporacion_id" = "id")
    ) %>% 
  left_join(
  tbl(con, "temas") %>%  select(id, tema = nombre),
  by = c("tema_id_principal" = "id")
  ) %>% 
    left_join(
    tbl(con, "tipo_proyectos") %>%  select(id, tipo_proyecto = nombre),
    by = c("tipo_proyecto_id" = "id")
  ) %>% 
  filter(tipo_proyecto=="Proyecto de Ley") %>% 
  filter(corporacion=="Senado de la República") %>% 
  filter(legislatura_id==27) %>% 
  count(tema) %>% 
  arrange(desc(n)) %>% 
  head(10)%>% 
  show_query()
  



```



```{r}

# temas <- read_csv(here("Para Jesús", "temas.csv")) %>% 
#          select(id, nombre) %>% 
#          rename("tema"="nombre")
# 
# proyecto_temas <- left_join(proyecto_final, temas, by=c("tema_id_principal"="id")) 

proyecto_temas_senado <- proyecto_final %>% 
                         filter(legislatura_id==max(legislatura_id) & corporacion=="Senado"& tipo_proyecto=="Proyecto de Ley") %>% 
                         count(tema) %>% 
                         arrange(desc(n)) %>% 
                         mutate(totales=sum(n, na.rm=T), 
                                porc=round((n/totales)*100, 1), 
                                tema=paste(tema, paste0(porc, "%"), sep="\n"))
                         
proyecto_temas_senado <- proyecto_temas_senado[1:10,]

  proyecto_temas_senado %>% 
  hchart(hcaes(x = tema,  value = n), type = "treemap")%>%
  hc_title(text = "Top 10: Temas de los proyectos de la ley en el Senado")%>%
  hc_add_theme(thm)


```
```{r}
tbl(con, "proyecto_leys") %>% 
  left_join(
  tbl(con, "legislaturas") %>% select(id, fechaInicio), 
  by = c("legislatura_id" = "id")) %>%  
    left_join(
      tbl(con, "corporacions") %>%  select(id, corporacion = nombre),
      by = c("corporacion_id" = "id")
    ) %>% 
  left_join(
  tbl(con, "temas") %>%  select(id, tema = nombre),
  by = c("tema_id_principal" = "id")
  ) %>% 
    left_join(
    tbl(con, "tipo_proyectos") %>%  select(id, tipo_proyecto = nombre),
    by = c("tipo_proyecto_id" = "id")
  ) %>% 
  filter(tipo_proyecto=="Proyecto de Ley") %>% 
  filter(corporacion=="Cámara de Representantes") %>% 
  filter(legislatura_id==27) %>% 
  count(tema) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  show_query()
  


```
```{r}
proyecto_temas_camara <- proyecto_final %>% 
                         filter(legislatura_id==max(legislatura_id) & corporacion!="Senado"& tipo_proyecto=="Proyecto de Ley") %>% 
                         count(tema) %>% 
                         arrange(desc(n))%>% 
                         mutate(totales=sum(n, na.rm=T), 
                                porc=round((n/totales)*100, 1), 
                                tema=paste(tema, paste0(porc, "%"), sep="\n"))
proyecto_temas_camara <- proyecto_temas_camara[1:10,]

  proyecto_temas_camara %>% 
  hchart(hcaes(x = tema,  value = n), type = "treemap")%>%
  hc_title(text = "Top 10: Temas de los proyectos de la ley en la Cámara de Representantes")%>%
  hc_add_theme(thm)

```

```{r}

 tbl(con, "proyecto_leys") %>% 
  select(id, legislatura_id, corporacion_id, tipo_proyecto_id)%>% 
  left_join(
  tbl(con, "legislaturas") %>% select(id, fechaInicio), 
  by = c("legislatura_id" = "id")) %>%  
    left_join(
      tbl(con, "corporacions") %>%  select(id, corporacion = nombre),
      by = c("corporacion_id" = "id")
    ) %>% 
    left_join(
    tbl(con, "tipo_proyectos") %>%  select(id, tipo_proyecto = nombre),
    by = c("tipo_proyecto_id" = "id")
  ) %>%
  left_join(
    tbl(con, "proyecto_ley_estados") %>%  select(proyecto_ley_id, estado_proyecto_ley_id),
    by = c("id" = "proyecto_ley_id")
  ) %>% 
  left_join(
    tbl(con, "estado_proyecto_leys") %>%  select(id, estado_proyecto = nombre),
    by = c("estado_proyecto_ley_id" = "id")
  ) %>% 
  filter(tipo_proyecto=="Proyecto de Ley") %>% 
  filter(corporacion=="Senado de la República") %>% 
  filter(legislatura_id==27) %>% 
  count(estado_proyecto) %>% 
  show_query()

```



```{r}
estado_proyecto_graf <- proyecto_final %>% 
                        filter(legislatura_id==max(legislatura_id) & corporacion=="Senado" & tipo_proyecto=="Proyecto de Ley")  %>% 
                        count(estado_proyecto)%>% 
                         mutate(totales=sum(n, na.rm=T), 
                                porc=round((n/totales)*100, 1), 
                                estado_proyecto=paste(estado_proyecto, paste0(porc, "%"), sep="\n")) 


  estado_proyecto_graf %>% 
  hchart(hcaes(x = estado_proyecto,  value = n), type = "treemap")%>%
  hc_title(text = "Estado de los proyectos de la ley en el Senado")%>%
  hc_add_theme(thm)


```

```{r}

 tbl(con, "proyecto_leys") %>% 
  select(id, legislatura_id, corporacion_id, tipo_proyecto_id)%>% 
  left_join(
  tbl(con, "legislaturas") %>% select(id, fechaInicio), 
  by = c("legislatura_id" = "id")) %>%  
    left_join(
      tbl(con, "corporacions") %>%  select(id, corporacion = nombre),
      by = c("corporacion_id" = "id")
    ) %>% 
    left_join(
    tbl(con, "tipo_proyectos") %>%  select(id, tipo_proyecto = nombre),
    by = c("tipo_proyecto_id" = "id")
  ) %>%
  left_join(
    tbl(con, "proyecto_ley_estados") %>%  select(proyecto_ley_id, estado_proyecto_ley_id),
    by = c("id" = "proyecto_ley_id")
  ) %>% 
  left_join(
    tbl(con, "estado_proyecto_leys") %>%  select(id, estado_proyecto = nombre),
    by = c("estado_proyecto_ley_id" = "id")
  ) %>% 
  filter(tipo_proyecto=="Proyecto de Ley") %>% 
  filter(corporacion=="Cámara de Representantes") %>% 
  filter(legislatura_id==27) %>% 
  count(estado_proyecto) %>% 
  show_query()

```

```{r}
estado_proyecto_graf <- proyecto_final %>% 
                        filter(legislatura_id==max(legislatura_id) & corporacion!="Senado" & tipo_proyecto=="Proyecto de Ley")  %>% 
                        count(estado_proyecto)%>% 
                         mutate(totales=sum(n, na.rm=T), 
                                porc=round((n/totales)*100, 1), 
                                estado_proyecto=paste(estado_proyecto, paste0(porc, "%"), sep="\n")) 


  estado_proyecto_graf %>% 
  hchart(hcaes(x = estado_proyecto,  value = n), type = "treemap")%>%
  hc_title(text = "Estado de los proyectos de la ley en la Cámara de Representantes")%>%
  hc_add_theme(thm)


```

```{r}


tbl(con, "proyecto_ley_autor_legislativos") %>% 
  select(proyecto_ley_id, congresista_id) %>% 
left_join(tbl(con, "proyecto_leys") %>% 
  select(id, legislatura_id, corporacion_id, tipo_proyecto_id),
  by=c("proyecto_ley_id"="id")) %>% 
  left_join(
  tbl(con, "legislaturas") %>% select(id, fechaInicio), 
  by = c("legislatura_id" = "id")) %>%  
    left_join(
      tbl(con, "corporacions") %>%  select(id, corporacion = nombre),
      by = c("corporacion_id" = "id")
    ) %>% 
  left_join(
  tbl(con, "tipo_proyectos") %>%  select(id, tipo_proyecto = nombre),
  by = c("tipo_proyecto_id" = "id")
  ) %>%
 left_join(
 tbl(con, "personas") %>%  select(id, nombres, apellidos),
 by = c("congresista_id" = "id")
  )%>% 
mutate(nombre_final=paste(nombres, apellidos, sep=" ")) %>% 
  filter(tipo_proyecto=="Proyecto de Ley") %>% 
  filter(corporacion=="Senado de la República") %>% 
  filter(legislatura_id==27) %>% 
  count(nombre_final) %>%  
  arrange(desc(n)) %>% 
  head(20) %>%
  show_query()






```




```{r}
personas <- read_csv(here("Para Jesús", "personas.csv")) %>% 
            select(id:apellidos) %>% 
            rename("persona_id"="id")

autor <- read_csv(here("Para Jesús", "proyecto_ley_autores_legislativos.csv")) %>% 
         filter(tipo_autor_id==28) %>%   
         select(proyecto_ley_id, persona_id)

proy_ley <- proyecto_final %>% 
            select(id, titulo, legislatura_id)
legis <- read_csv(here::here("Para Jesús", "legislaturas.csv"))
autor <- left_join(autor, proy_ley, by=c("proyecto_ley_id"="id"))
autor <- left_join(autor, personas, by="persona_id")
autor <- left_join(autor, congresistas, by="persona_id")



autor_suma_sen <- autor %>%
              filter(legislatura_id==max(legislatura_id, na.rm = T)) %>% 
              # filter(!is.na(nombres) | !is.na(apellidos)) %>% 
              filter(corporacion_id==1) %>% 
              mutate(nombre_final=paste(nombres, apellidos, sep=" ")) %>% 
              count(nombre_final) %>% 
              arrange(desc(n))
autor_suma_sen <- autor_suma_sen[1:20,]
autor_suma_sen %>% 
   hchart(hcaes(x = nombre_final, y = n), type = "lollipop") %>% 
 hc_title(text = "Senadores con mayor número de autorías de proyectos de ley")%>%
  hc_add_theme(thm) %>% 
  hc_chart(inverted = T)%>% 
  hc_xAxis(title = list(text = " ")) %>%
  hc_yAxis(title = list(text = "Total"))

```
```{r}


tbl(con, "proyecto_ley_autor_legislativos") %>% 
  select(proyecto_ley_id, congresista_id) %>% 
left_join(tbl(con, "proyecto_leys") %>% 
  select(id, legislatura_id, corporacion_id, tipo_proyecto_id),
  by=c("proyecto_ley_id"="id")) %>% 
  left_join(
  tbl(con, "legislaturas") %>% select(id, fechaInicio), 
  by = c("legislatura_id" = "id")) %>%  
    left_join(
      tbl(con, "corporacions") %>%  select(id, corporacion = nombre),
      by = c("corporacion_id" = "id")
    ) %>% 
  left_join(
  tbl(con, "tipo_proyectos") %>%  select(id, tipo_proyecto = nombre),
  by = c("tipo_proyecto_id" = "id")
  ) %>%
 left_join(
 tbl(con, "personas") %>%  select(id, nombres, apellidos),
 by = c("congresista_id" = "id")
  ) %>% 
mutate(nombre_final=paste(nombres, apellidos, sep=" ")) %>% 
  filter(tipo_proyecto=="Proyecto de Ley") %>% 
  filter(corporacion=="Cámara de Representantes") %>% 
  filter(legislatura_id==27) %>% 
  count(nombre_final) %>%  
  arrange(desc(n)) %>% 
  head(20) %>%
  show_query()





```

```{r}

autor_suma_rep <- autor %>%
              filter(legislatura_id==max(legislatura_id, na.rm = T)) %>% 
              # filter(!is.na(nombres) | !is.na(apellidos)) %>% 
              filter(corporacion_id!=1) %>% 
              mutate(nombre_final=paste(nombres, apellidos, sep=" ")) %>% 
              count(nombre_final) %>% 
              arrange(desc(n))
autor_suma_rep <- autor_suma_rep[1:20,]
autor_suma_rep %>% 
   hchart(hcaes(x = nombre_final, y = n), type = "lollipop") %>% 
  hc_title(text = "Representantes con mayor número de autorías de proyectos de ley")%>%
  hc_add_theme(thm)%>%
  hc_add_theme(thm) %>% 
  hc_chart(inverted = T)%>% 
  hc_xAxis(title = list(text = " ")) %>%
  hc_yAxis(title = list(text = "Total"))

```


```{r}
tbl(con, "proyecto_ley_autor_legislativos") %>% 
  select(proyecto_ley_id, congresista_id) %>% 
left_join(tbl(con, "proyecto_leys") %>% 
  select(id, legislatura_id, corporacion_id, tipo_proyecto_id),
  by=c("proyecto_ley_id"="id")) %>% 
  left_join(
  tbl(con, "legislaturas") %>% select(id, fechaInicio), 
  by = c("legislatura_id" = "id")) %>%  
    left_join(
      tbl(con, "corporacions") %>%  select(id, corporacion = nombre),
      by = c("corporacion_id" = "id")
    ) %>% 
  left_join(
  tbl(con, "tipo_proyectos") %>%  select(id, tipo_proyecto = nombre),
  by = c("tipo_proyecto_id" = "id")
  ) %>%
 left_join(
 tbl(con, "personas") %>%  select(id, nombres, apellidos),
 by = c("congresista_id" = "id")
  ) %>%
 left_join(
 tbl(con, "congresistas") %>%  select(persona_id, partido_id),
 by = c("congresista_id" = "persona_id")
  )%>%
 left_join(
 tbl(con, "partidos") %>%  select(id, partido=nombre),
 by = c("partido_id" = "id")
  )  %>% 
  filter(tipo_proyecto=="Proyecto de Ley") %>% 
  filter(corporacion=="Senado de la República") %>% 
  filter(legislatura_id==27) %>% 
  count(partido) %>%  
  arrange(desc(n)) %>% 
  show_query()



```




```{r}

#Partidos

partidos <- read_csv(here("Para Jesús", "partidos.csv")) %>% 
            select(partido_id=id, partido=nombre)

autor <- left_join(autor, partidos, by="partido_id")
partidos_suma_sen <- autor %>%
              filter(legislatura_id==max(legislatura_id, na.rm = T)) %>% 
              filter(corporacion_id==1) %>% 
              count(partido) %>% 
              arrange(desc(n))


partidos_suma_sen %>% 
   hchart(hcaes(x = partido, y = n), type = "lollipop") %>% 
 hc_title(text = "Partidos con mayor número de autorías de proyectos de ley, en el Senado")%>%
  hc_add_theme(thm) %>%
  hc_add_theme(thm) %>% 
  hc_chart(inverted = T)%>% 
  hc_xAxis(title = list(text = "")) %>%
  hc_yAxis(title = list(text = "Total"))




```


```{r}
tbl(con, "proyecto_ley_autor_legislativos") %>% 
  select(proyecto_ley_id, congresista_id) %>% 
left_join(tbl(con, "proyecto_leys") %>% 
  select(id, legislatura_id, corporacion_id, tipo_proyecto_id),
  by=c("proyecto_ley_id"="id")) %>% 
  left_join(
  tbl(con, "legislaturas") %>% select(id, fechaInicio), 
  by = c("legislatura_id" = "id")) %>%  
    left_join(
      tbl(con, "corporacions") %>%  select(id, corporacion = nombre),
      by = c("corporacion_id" = "id")
    ) %>% 
  left_join(
  tbl(con, "tipo_proyectos") %>%  select(id, tipo_proyecto = nombre),
  by = c("tipo_proyecto_id" = "id")
  ) %>%
 left_join(
 tbl(con, "personas") %>%  select(id, nombres, apellidos),
 by = c("congresista_id" = "id")
  ) %>%
 left_join(
 tbl(con, "congresistas") %>%  select(persona_id, partido_id),
 by = c("congresista_id" = "persona_id")
  )%>%
 left_join(
 tbl(con, "partidos") %>%  select(id, partido=nombre),
 by = c("partido_id" = "id")
  )  %>% 
  filter(tipo_proyecto=="Proyecto de Ley") %>% 
  filter(corporacion=="Cámara de Representantes") %>% 
  filter(legislatura_id==27) %>% 
  count(partido) %>%  
  arrange(desc(n)) %>% 
  show_query()



```




```{r}


partidos_suma_rep <- autor %>%
              filter(legislatura_id==max(legislatura_id, na.rm = T)) %>% 
              filter(corporacion_id!=1) %>% 
              count(partido) %>% 
              arrange(desc(n))


partidos_suma_rep %>% 
   hchart(hcaes(x = partido, y = n), type = "lollipop") %>% 
 hc_title(text = "Partidos con mayor número de autorías de proyectos de ley, en la Cámara de Representantes")%>%
  hc_add_theme(thm)%>%
  hc_add_theme(thm) %>% 
  hc_chart(inverted = T)%>% 
  hc_xAxis(title = list(text = "")) %>%
  hc_yAxis(title = list(text = "Total"))


```

```{r}
tbl(con, "proyecto_ley_autor_legislativos") %>% 
  select(proyecto_ley_id, congresista_id) %>% 
left_join(tbl(con, "proyecto_leys") %>% 
  select(id, legislatura_id, corporacion_id, tipo_proyecto_id, tema_id_principal),
  by=c("proyecto_ley_id"="id")) %>% 
  left_join(
  tbl(con, "legislaturas") %>% select(id, fechaInicio), 
  by = c("legislatura_id" = "id")) %>%  
    left_join(
      tbl(con, "corporacions") %>%  select(id, corporacion = nombre),
      by = c("corporacion_id" = "id")
    ) %>% 
  left_join(
  tbl(con, "tipo_proyectos") %>%  select(id, tipo_proyecto = nombre),
  by = c("tipo_proyecto_id" = "id")
  ) %>%
 left_join(
 tbl(con, "personas") %>%  select(id, nombres, apellidos),
 by = c("congresista_id" = "id")
  ) %>%
 left_join(
 tbl(con, "congresistas") %>%  select(persona_id, partido_id),
 by = c("congresista_id" = "persona_id")
  )%>%
 left_join(
 tbl(con, "partidos") %>%  select(id, partido=nombre),
 by = c("partido_id" = "id")
  ) %>%  
  left_join(
  tbl(con, "temas") %>%  select(id, tema = nombre),
  by = c("tema_id_principal" = "id")
  )  %>% 
  filter(tipo_proyecto=="Proyecto de Ley") %>% 
  filter(corporacion=="Senado de la República") %>% 
  filter(legislatura_id==27) %>% 
  count(partido, tema) %>%  
  arrange(desc(n)) %>% 
 filter(n>=30)  %>% 
show_query()



```

```{r}

proy_temas <- proyecto_final %>% 
              select(proyecto_ley_id=id, tema)

autor <- left_join(autor, proy_temas, by="proyecto_ley_id")
autor <- left_join(autor, corpo, by=c("corporacion_id"="id"))

partido_temas_sen<- autor %>% 
              filter(legislatura_id==max(legislatura_id, na.rm = T)) %>% 
              filter(corporacion=="Senado") %>% 
              count(partido, tema) %>% 
              group_by(partido) %>% 
              filter(n>=30) %>% 
              ungroup()


partido_temas_sen %>% 
  hchart(hcaes(from = partido, to  = tema, weight =n), type = "sankey") %>%
  hc_title(text = "Temas recurrentes por partido político en el Senado")%>%
  hc_add_theme(thm)

```
```{r}
tbl(con, "proyecto_ley_autor_legislativos") %>% 
  select(proyecto_ley_id, congresista_id) %>% 
left_join(tbl(con, "proyecto_leys") %>% 
  select(id, legislatura_id, corporacion_id, tipo_proyecto_id, tema_id_principal),
  by=c("proyecto_ley_id"="id")) %>% 
  left_join(
  tbl(con, "legislaturas") %>% select(id, fechaInicio), 
  by = c("legislatura_id" = "id")) %>%  
    left_join(
      tbl(con, "corporacions") %>%  select(id, corporacion = nombre),
      by = c("corporacion_id" = "id")
    ) %>% 
  left_join(
  tbl(con, "tipo_proyectos") %>%  select(id, tipo_proyecto = nombre),
  by = c("tipo_proyecto_id" = "id")
  ) %>%
 left_join(
 tbl(con, "personas") %>%  select(id, nombres, apellidos),
 by = c("congresista_id" = "id")
  ) %>%
 left_join(
 tbl(con, "congresistas") %>%  select(persona_id, partido_id),
 by = c("congresista_id" = "persona_id")
  )%>%
 left_join(
 tbl(con, "partidos") %>%  select(id, partido=nombre),
 by = c("partido_id" = "id")
  ) %>%  
  left_join(
  tbl(con, "temas") %>%  select(id, tema = nombre),
  by = c("tema_id_principal" = "id")
  )  %>% 
  filter(tipo_proyecto=="Proyecto de Ley") %>% 
  filter(corporacion=="Cámara de Representantes") %>% 
  filter(legislatura_id==27) %>% 
  count(partido, tema) %>%  
  arrange(desc(n)) %>% 
 filter(n>=30)  %>% 
show_query()


```

```{r}



partido_temas_sen<- autor %>% 
              filter(legislatura_id==max(legislatura_id, na.rm = T)) %>% 
              filter(corporacion!="Senado") %>% 
              count(partido, tema) %>% 
              group_by(partido) %>% 
              filter(n>=30) %>% 
              ungroup()


partido_temas_sen %>% 
  hchart(hcaes(from = partido, to  = tema, weight =n), type = "sankey") %>%
  hc_title(text = "Temas recurrentes por partido político en la Cámara de Representantes")%>%
  hc_add_theme(thm)

```
