---
title: "Congreso Hoy"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = F, 
message = F,
warning = F, 
fig.asp = 0.8, 
fig.width = 7, 
out.width = "100%",
dpi = 300,
collapse = TRUE,
comment = "#>"
) 
```


```{r, include = FALSE}
library(pacman)
p_load(tidyverse, magrittr, highcharter, lubridate, devtools, viridis, hrbrthemes, mapdata, here)
library(ggchicklet)
library(randomNames)

```




```{r}
pal <- colorRampPalette(c("#66CCFF", "#17789E", "#6AEEB0", "#379E80", "#F78031", "#374B9E", "#666666"))
thm <- hc_theme(
  colors = c("#66CCFF", "#17789E", "#6AEEB0", "#379E80", "#F78031", "#374B9E"),
  chart = list( style = list(fontFamily = "Bell MT", fontSize = "20px")),
  title = list( style = list(  color = "#17789E", fontSize = "22px", fontWeight= 'bold')),
  subtitle = list(  style = list(    color = "#666666"  ) ),
  legend = list( itemStyle = list(  color = "black"   ),
                 itemHoverStyle = list( color = "gray")  ),
  tooltip = list(borderWidth =0, shadow = F, style = list( fontSize = "16px")),
  yAxis = list(lineWidth = 3,title = list(style= list(fontSize = "16px")),
               tickAmount = 5,
               labels = list(style= list(fontSize = "15px"))),
  xAxis = list(lineWidth = 0,title = list(style= list(fontSize = "16px")),
               labels = list(style= list(fontSize = "18px"))),
  plotOptions = list(bar = list(borderRadius =5), treemap = list(borderRadius =5, colorByPoint = T))
)
proyecto <- read_csv(here("Para Jesús", "proyecto_leys.csv"))

iniciativas <- read_csv(here("Para Jesús", "iniciativas.csv")) %>% 
               select(id, nombre) %>% 
               rename("iniciativa"="nombre")
tipo_proyecto <- read_csv(here("Para Jesús", "tipo_proyectos.csv")) %>% 
               select(id, nombre)%>% 
               rename("tipo_proyecto"="nombre")
legis <- read_csv(here("Para Jesús", "legislaturas.csv")) %>% 
               select(id:fechaFin) %>% 
               rename("legislatura"="nombre")
corpo <- read_csv(here("Para Jesús", "corporacions.csv")) %>% 
               select(id, nombre)%>% 
               rename("corporacion"="nombre")
proyecto_estado <- read_csv(here("Para Jesús", "proyecto_ley_estados.csv")) %>% 
                   select(proyecto_ley_id, estado_proyecto_ley_id, fecha)
estado_proyecto <- read_csv(here("Para Jesús", "estado_proyecto_leys.csv")) %>% 
                   select(id, nombre) %>% 
                   rename("estado_proyecto"="nombre")
estado_final <- left_join(proyecto_estado, estado_proyecto, by=c("estado_proyecto_ley_id"="id")) %>% 
                select(fecha, proyecto_ley_id, estado_proyecto) %>% 
                group_by(proyecto_ley_id) %>% 
                filter(fecha==max(fecha)) %>% 
                ungroup()



cuatri <- read_csv(here("Para Jesús", "cuatrienios.csv"))

proyecto_final <- left_join(proyecto, iniciativas, by=c("iniciativa_id"="id"))

proyecto_final <- left_join(proyecto_final, tipo_proyecto, by=c("tipo_proyecto_id"="id"))

proyecto_final <- left_join(proyecto_final, legis, by=c("legislatura_id"="id"))

proyecto_final <- left_join(proyecto_final, corpo, by=c("corporacion_id"="id"))

proyecto_final <- inner_join(proyecto_final, estado_final, by=c("id" ="proyecto_ley_id"))







```


# Proyectos de ley

### Origen de las iniciativas

```{r}
proyecto_final_senado <- proyecto_final %>% 
                         filter(legislatura_id==max(legislatura_id) & corporacion=="Senado" & tipo_proyecto=="Proyecto de Ley")  %>% 
                         count(tipo_proyecto, iniciativa) %>% 
                         arrange(desc(n))



```


```{r}

  proyecto_final_senado %>% 
  hchart(hcaes(x = iniciativa, y = n), type = "bar") %>% 
  hc_title(text = "Origen de las iniciativas en el Senado")%>%
  
  hc_add_theme(thm) %>% 
  hc_xAxis(title = list(text = "Iniciativa")) %>%
  hc_yAxis(title = list(text = "Total")) %>% 
 hc_plotOptions(bar=list(borderRadius =5, colorByPoint = T))%>%
  hc_tooltip(pointFormat = '<b>{point.n}</b>')


```




```{r}
proyecto_final_camara <- proyecto_final %>% 
                         filter(legislatura_id==max(legislatura_id) & corporacion!="Senado"& tipo_proyecto=="Proyecto de Ley") %>% 
                         count(tipo_proyecto, iniciativa) %>% 
                         arrange(desc(n))

```


```{r}


  proyecto_final_camara %>% 
  hchart(hcaes(x = iniciativa, y = n), type = "bar") %>% 
  hc_title(text = "Origen de las iniciativas en la Cámara de Representantes")%>%
  hc_add_theme(thm)%>% 
  hc_xAxis(title = list(text = "Iniciativa")) %>%
  hc_yAxis(title = list(text = "Total"), tickAmount = 6)%>% 
 hc_plotOptions(bar=list(borderRadius =5, colorByPoint = T))%>%
  hc_tooltip(pointFormat = '<b>{point.n}</b> ')


```



### Temas de los proyectos de ley

```{r}

temas <- read_csv(here("Para Jesús", "temas.csv")) %>% 
         select(id, nombre) %>% 
         rename("tema"="nombre")

proyecto_temas <- left_join(proyecto_final, temas, by=c("tema_id_principal"="id")) 

proyecto_temas_senado <- proyecto_temas %>% 
                         filter(legislatura_id==max(legislatura_id) & corporacion=="Senado"& tipo_proyecto=="Proyecto de Ley") %>% 
                         count(tema) %>% 
                         arrange(desc(n)) 
                         
proyecto_temas_senado <- proyecto_temas_senado[1:10,]

  proyecto_temas_senado %>% 
  hchart(hcaes(x = tema,  value = n), type = "treemap")%>%
  hc_title(text = "Top 10: Temas de los proyectos de la ley en el Senado")%>%
  hc_add_theme(thm)


```


```{r}
proyecto_temas_camara <- proyecto_temas %>% 
                         filter(legislatura_id==max(legislatura_id) & corporacion!="Senado"& tipo_proyecto=="Proyecto de Ley") %>% 
                         count(tema) %>% 
                         arrange(desc(n)) 
                         
proyecto_temas_camara <- proyecto_temas_camara[1:10,]

  proyecto_temas_camara %>% 
  hchart(hcaes(x = tema,  value = n), type = "treemap")%>%
  hc_title(text = "Top 10: Temas de los proyectos de la ley en la Cámara de Representantes")%>%
  hc_add_theme(thm)




```


### Estados de los proyectos de ley



```{r}
estado_proyecto_graf <- proyecto_final %>% 
                        filter(legislatura_id==max(legislatura_id) & corporacion=="Senado" & tipo_proyecto=="Proyecto de Ley")  %>% 
                        count(estado_proyecto) 


  estado_proyecto_graf %>% 
  hchart(hcaes(x = estado_proyecto,  value = n), type = "treemap")%>%
  hc_title(text = "Estado de los proyectos de la ley en el Senado")%>%
  hc_add_theme(thm)


```


```{r}
estado_proyecto_graf <- proyecto_final %>% 
                        filter(legislatura_id==max(legislatura_id) & corporacion=="Senado" & tipo_proyecto=="Proyecto de Ley")  %>% 
                        count(iniciativa, estado_proyecto) 

estado_proyecto_graf %>% 
  hchart(hcaes(from = iniciativa, to  = estado_proyecto, weight =n), type = "sankey") %>%
 hc_title(text = "Estado del proyecto, según origen de las iniciativas en el Senado") %>% 
  hc_add_theme(thm)


```

```{r}
estado_proyecto_graf_camara <- proyecto_final %>% 
                        filter(legislatura_id==max(legislatura_id) & corporacion!="Senado" & tipo_proyecto=="Proyecto de Ley")  %>% 
                        count(estado_proyecto) 
  estado_proyecto_graf_camara %>% 
  hchart(hcaes(x = estado_proyecto,  value = n), type = "treemap")%>%
  hc_title(text = "Estado de los proyectos de la ley en la Cámara de Representantes")%>%
  hc_add_theme(thm)

```

```{r}
estado_proyecto_graf_camara <- proyecto_final %>% 
                        filter(legislatura_id==max(legislatura_id) & corporacion!="Senado" & tipo_proyecto=="Proyecto de Ley")  %>% 
                        count(iniciativa, estado_proyecto) 

estado_proyecto_graf_camara %>% 
  hchart(hcaes(from = iniciativa, to  = estado_proyecto, weight =n), type = "sankey") %>%
  hc_title(text = "Estado del proyecto, según origen de las iniciativas en la Cámara de Representantes")%>%
  hc_add_theme(thm)


```


# Congresistas más activos


```{r}
# citantes <- read_csv(here("Bases de datos nuevas", "control_politico_citantes.csv"))
citantes <- read_csv(here("Para Jesús", "control_politico_citantes.csv"))

citacions <- read_csv(here("Para Jesús", "control_politicos.csv")) %>% 
             select(id, legislatura_id, fecha) %>% 
             unique() %>% 
             rename("control_politico_id"="id")

personas <- read_csv(here("Para Jesús", "personas.csv")) %>% 
            select(id:apellidos) %>% 
            rename("persona_id"="id")

congresistas <- read_csv(here("Para Jesús", "congresistas.csv")) %>% 
                select(id:partido_id) %>% 
                rename("congresista_id"="id")


citantes <- left_join(citantes, citacions, by="control_politico_id")
citantes <- left_join(citantes, congresistas, by="congresista_id")
citantes <- left_join(citantes, personas, by="persona_id")

citantes <- left_join(citantes, corpo, by=c("corporacion_id"="id"))


citan_suma_se <- citantes %>%
              filter(legislatura_id==max(legislatura_id, na.rm=T)) %>%
              filter(corporacion!="Senado") %>%
              # filter(!is.na(nombres) | !is.na(apellidos)) %>% 
              mutate(nombre_final=paste(nombres, apellidos, sep=" ")) %>% 
              count(nombre_final) %>% 
              arrange(desc(n))

  citan_suma_se %>% 
  hchart(hcaes(x = nombre_final, y = n), type = "bar") %>% 
  hc_title(text = "Representantes con mayor número de citaciones de Debates de Control Político")%>%
  hc_add_theme(thm)%>% 
  hc_xAxis(title = list(text = "")) %>%
  hc_yAxis(title = list(text = "Total"), allowDecimals=F)

```

```{r}
citan_suma_re <- citantes %>%
              filter(legislatura_id==max(legislatura_id, na.rm=T)) %>%
              filter(corporacion=="Senado") %>%
              filter(!is.na(nombres) | !is.na(apellidos)) %>% 
              mutate(nombre_final=paste(nombres, apellidos, sep=" ")) %>% 
              count(nombre_final) %>% 
              arrange(desc(n))
citan_suma_re %>% 
   hchart(hcaes(x = nombre_final, y = n), type = "bar") %>% 
  hc_title(text = "Senadores con mayor número de citaciones de Debates de Control Político")%>%
  hc_add_theme(thm)%>% 
  hc_xAxis(title = list(text = "")) %>%
  hc_yAxis(title = list(text = "Total"), allowDecimals=F)



```


```{r}

autor <- read_csv(here("Para Jesús", "proyecto_ley_autors.csv")) %>% 
         filter(tipo_autor_id==28) %>%   
         select(proyecto_ley_id, congresista_id)

proy_ley <- proyecto_final %>% 
            select(id, titulo, legislatura_id)
legis <- read_csv(here::here("Para Jesús", "legislaturas.csv"))
autor <- left_join(autor, proy_ley, by=c("proyecto_ley_id"="id"))
autor <- left_join(autor, personas, by=c("congresista_id"="persona_id"))
autor <- left_join(autor, congresistas, by="congresista_id")



autor_suma_sen <- autor %>%
              filter(legislatura_id==max(legislatura_id, na.rm = T)) %>% 
              # filter(!is.na(nombres) | !is.na(apellidos)) %>% 
              filter(corporacion_id==1) %>% 
              mutate(nombre_final=paste(nombres, apellidos, sep=" ")) %>% 
              count(nombre_final) %>% 
              arrange(desc(n))
autor_suma_sen <- autor_suma_sen[1:20,]
autor_suma_sen %>% 
   hchart(hcaes(x = nombre_final, y = n), type = "lollipop") %>% 
 hc_title(text = "Senadores con mayor número de autorías de proyectos de ley")%>%
  hc_add_theme(thm) %>% 
  hc_chart(inverted = T)%>% 
  hc_xAxis(title = list(text = " ")) %>%
  hc_yAxis(title = list(text = "Total"))


```



```{r}
autor_suma_rep <- autor %>%
              filter(legislatura_id==max(legislatura_id, na.rm = T)) %>% 
              # filter(!is.na(nombres) | !is.na(apellidos)) %>% 
              filter(corporacion_id!=1) %>% 
              mutate(nombre_final=paste(nombres, apellidos, sep=" ")) %>% 
              count(nombre_final) %>% 
              arrange(desc(n))
autor_suma_rep <- autor_suma_rep[1:20,]
autor_suma_rep %>% 
   hchart(hcaes(x = nombre_final, y = n), type = "lollipop") %>% 
  hc_title(text = "Representantes con mayor número de autorías de proyectos de ley")%>%
  hc_add_theme(thm)%>%
  hc_add_theme(thm) %>% 
  hc_chart(inverted = T)%>% 
  hc_xAxis(title = list(text = " ")) %>%
  hc_yAxis(title = list(text = "Total"))





```


# Actividad por partidos políticos

```{r}

#Partidos

partidos <- read_csv(here("Para Jesús", "partidos.csv")) %>% 
            select(partido_id=id, partido=nombre)

autor <- left_join(autor, partidos, by="partido_id")
partidos_suma_rep <- autor %>%
              filter(legislatura_id==max(legislatura_id, na.rm = T)) %>% 
              filter(corporacion_id!=1) %>% 
              count(partido) %>% 
              arrange(desc(n))


partidos_suma_rep %>% 
   hchart(hcaes(x = partido, y = n), type = "lollipop") %>% 
 hc_title(text = "Partidos con mayor número de autorías de proyectos de ley, en la Cámara de Representantes")%>%
  hc_add_theme(thm)%>%
  hc_add_theme(thm) %>% 
  hc_chart(inverted = T)%>% 
  hc_xAxis(title = list(text = "")) %>%
  hc_yAxis(title = list(text = "Total"))


```
```{r}
partidos_suma_sen <- autor %>%
              filter(legislatura_id==max(legislatura_id, na.rm = T)) %>% 
              filter(corporacion_id==1) %>% 
              count(partido) %>% 
              arrange(desc(n))


partidos_suma_sen %>% 
   hchart(hcaes(x = partido, y = n), type = "lollipop") %>% 
 hc_title(text = "Partidos con mayor número de autorías de proyectos de ley, en el Senado")%>%
  hc_add_theme(thm) %>%
  hc_add_theme(thm) %>% 
  hc_chart(inverted = T)%>% 
  hc_xAxis(title = list(text = "")) %>%
  hc_yAxis(title = list(text = "Total"))



```













```{r}


citantes <- left_join(citantes, partidos, by="partido_id")

citan_partido_sen <- citantes %>%
              filter(legislatura_id==max(legislatura_id, na.rm=T)) %>%
              filter(corporacion=="Senado") %>%
              count(partido) %>% 
              arrange(desc(n))
citan_partido_sen %>% 
   hchart(hcaes(x = partido, y = n), type = "bar") %>% 
  hc_title(text = "Partidos en el Senado con mayor número de citaciones de Debates de Control Político")%>%
  hc_add_theme(thm)%>% 
  hc_xAxis(title = list(text = "")) %>%
  hc_yAxis(title = list(text = "Total"))




```


```{r}

citan_partido_re <- citantes %>%
              filter(legislatura_id==max(legislatura_id, na.rm=T)) %>%
              filter(corporacion!="Senado") %>%
              count(partido) %>% 
              arrange(desc(n))
citan_partido_re %>% 
   hchart(hcaes(x = partido, y = n), type = "bar") %>% 
  hc_title(text = "Partidos en la Cámara de Representantes con mayor número de citaciones de Debates de Control Político")%>%
  hc_add_theme(thm) %>% 
  hc_xAxis(title = list(text = "")) %>%
  hc_yAxis(title = list(text = "Total"))


```

```{r}

proy_temas <- proyecto_temas %>% 
              select(proyecto_ley_id=id, tema)

autor <- left_join(autor, proy_temas, by="proyecto_ley_id")
autor <- left_join(autor, corpo, by=c("corporacion_id"="id"))

partido_temas_sen<- autor %>% 
              filter(legislatura_id==max(legislatura_id, na.rm = T)) %>% 
              filter(corporacion=="Senado") %>% 
              count(partido, tema) %>% 
              group_by(partido) %>% 
              filter(n>=mean(n)) %>% 
              ungroup()


partido_temas_sen %>% 
  hchart(hcaes(from = partido, to  = tema, weight =n), type = "sankey") %>%
  hc_title(text = "Temas recurrentes por partido político en el Senado")%>%
  hc_add_theme(thm)



```


```{r}

partido_temas_rep<- autor %>% 
              filter(legislatura_id==max(legislatura_id, na.rm = T)) %>% 
              filter(corporacion!="Senado") %>% 
              count(partido, tema) %>% 
              group_by(partido) %>% 
              filter(n>=mean(n)) %>% 
              ungroup()

partido_temas_rep %>% 
  hchart(hcaes(from = partido, to  = tema, weight =n), type = "sankey") %>%
  hc_title(text = "Temas recurrentes por partido político en el Senado")%>%
  hc_add_theme(thm)




```


```{r}

citados <- read_csv(here::here("Bases de datos nuevas", "control_politico_citados.csv"))



```


